name: Generate Precompiled

on:
  push:
    paths:
      - "src/**"
      - "include/**"
      - "lib/**"
  pull_request:
    paths:
      - "src/**"
      - "include/**"
      - "lib/**"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: '0.15.1'

      - name: Run build script
        run: ./scripts/generate_precompiled.sh
